image:
  pullPolicy: Always

service:
  targetPort: 5000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: 
    enabled: true
    secretName: kube-benco-io-cert