name: Demo

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  buildJob:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - run: echo "foooooooo"
